<a href="https://colab.research.google.com/github/andrecamara2004/andrecamara2004.github.io/blob/main/0torch_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises Deep Learning
First Lecture

## Basic Tensor Operations


In [1]:
import torch
import torch.nn as nn
import numpy as np

In [26]:
x = torch.Tensor(2, 3, 4)
print(x)

tensor([[[-9.8384e-20,  4.3408e-41, -1.8714e+01,  3.1941e-41],
         [ 4.4842e-44,  0.0000e+00,  1.1210e-43,  0.0000e+00],
         [ 4.5339e+10,  3.1948e-41,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])


Different ways to create tensors:
- ```torch.zeros```: Creates a tensor filled with zeros
- ```torch.ones```: Creates a tensor filled with ones
- ```torch.rand```: Creates a tensor with random values uniformly sampled between 0 and 1
- ```torch.randn```: Creates a tensor with random values sampled from a normal distribution with mean 0 and variance 1
- ```torch.arange```: Creates a tensor containing the values
- ```torch.Tensor``` (input list): Creates a tensor from the list elements you provide

You can obtain the shape of a tensor in the same way as in numpy (```x.shape```), or using the ```.size``` method:

In [3]:
shape = x.shape
print("Shape:", x.shape)

size = x.size()
print("Size:", size)

dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


Tensor to Numpy, and Numpy to Tensor


In [4]:
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]])


In [5]:
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


Matrix multiplication

In [6]:
x = torch.arange(6)
x = x.view(2, 3)
print("X", x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [7]:
W = torch.arange(9).view(3, 3) # We can also stack multiple operations in a single line
print("W", W)

W tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [8]:
h = torch.matmul(x, W) # Verify the result by calculating it by hand too!
print("h", h)

h tensor([[15, 18, 21],
        [42, 54, 66]])


 ### What about gpus?

When you create a tensor the tensor is ready to be computed by the cpu. To convert the tensor you can use ```.to()```
passing to the function "cuda" or "cpu" as needed

#### How do I know if I have cuda cores on my computer?
To solve this you can check with torch if cuda is available:

In [9]:
example_tensor = torch.rand(2,2)
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU for PyTorch.")
    example_tensor.to("cuda")
else:
    print("CUDA is not available. Using CPU for PyTorch.")
    example_tensor.to("cpu")

CUDA is not available. Using CPU for PyTorch.


### Exercises

#### 1. Create two tensors

   - A 3x3 tensor of random numbers.
   - A 3x3 tensor filled with ones.

In [10]:
a = torch.rand(3,3)
b = torch.ones(3,3)


#### 2. Perform the following operations

- Add the two tensors.
- Multiply the two tensors element-wise.
- Compute the dot product between the first row of both tensors.
 - Find the transpose of the resulting tensor from the element-wise multiplication.

In [11]:
#add the two sensors
add = a + b
print(add)
#multiply the two sensores element-wise
multiply = a * b
print(multiply)
#compute the dot product between the first row of both tensors
dot_product = torch.dot(a[0], b[0])
print(dot_product)

tensor([[1.6507, 1.8458, 1.5287],
        [1.8784, 1.4132, 1.7012],
        [1.7594, 1.3103, 1.2015]])
tensor([[0.6507, 0.8458, 0.5287],
        [0.8784, 0.4132, 0.7012],
        [0.7594, 0.3103, 0.2015]])
tensor(2.0253)


#### 3. Convert the resulting tensor to a NumPy array and back to a PyTorch tensor.

In [12]:
#Convert the resulting tensor to a NumPy array and back to a PyTorch tensor.
numpy_array = add.numpy()
print(numpy_array)
pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1.6507107 1.8458431 1.5287322]
 [1.8783845 1.4131838 1.701165 ]
 [1.7593975 1.3103219 1.2015214]]
tensor([[1.6507, 1.8458, 1.5287],
        [1.8784, 1.4132, 1.7012],
        [1.7594, 1.3103, 1.2015]])


## Autograd

1. Create Tensors

In [13]:
x_a = torch.tensor(0., requires_grad=True)
x_b = torch.tensor(0., requires_grad=True)
w_a = torch.tensor(0.9, requires_grad=True)
w_b = torch.tensor(0.9, requires_grad=True)

y = torch.tensor(0., requires_grad=False)

2. Build a computation graph

In [14]:
weighted_a = w_a * x_a
weighted_b = w_b * x_b
sum_unit = weighted_a + weighted_b

3. Activation Function

For a simple approach as ease of replication by hand we will this activation function:

In [15]:
y_hat = torch.sigmoid(sum_unit)

4. Calculate Loss

In [16]:
loss = torch.nn.BCELoss()
output = loss(y_hat, y)

5. Calculate gradients

In [17]:
output.backward()

6.Print out the gradients

In [18]:
print(x_a.grad)
print(x_b.grad)
print(w_a.grad)
print(w_b.grad)

tensor(0.4500)
tensor(0.4500)
tensor(0.)
tensor(0.)


### Training Loop

In [19]:
learning_rate = 0.1
epochs = 100

input_data = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
target_data = torch.tensor([[0], [0], [0], [1]], dtype=torch.float32)

In [20]:
class ANDGateModel(nn.Module):
    def __init__(self):
        super(ANDGateModel, self).__init__()
        self.linear = nn.Linear(2, 1,bias=True)

    def forward(self, x):
        x = self.linear(x)
        x = torch.sigmoid(x)
        return x


In [21]:
# Initialize the model
model = ANDGateModel()

# Loss function (Binary Cross-Entropy Loss)
loss_fn = torch.nn.BCELoss()

# Optimizer (Stochastic Gradient Descent)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
for epoch in range(epochs):
    y_hat = model(input_data)
    loss = loss_fn(y_hat, target_data)


    loss.backward() # Backpropagation
    optimizer.step() # Update parameters using the optimizer
    optimizer.zero_grad() # Zero the gradients for the next iteration

    # Print loss and progress every 1000 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}/{epochs}, Loss: {loss.item():.4f}")

# Final weights and bias (optional)
print(f"Final weights: {model.linear.weight.data}")
print(f"Final bias: {model.linear.bias.data}")

# Test the AND gate
with torch.no_grad():
    for i in range(len(input_data)):
        x_a, x_b = input_data[i]
        y_hat = model(torch.tensor([[x_a, x_b]]))  # Model expects a batch
        print(f"Input: {input_data[i].numpy()} -> Predicted Output: {round(y_hat.item())}, Raw Output: {y_hat.item():.4f}")


Epoch 100/100, Loss: 0.0892
Final weights: tensor([[4.1687, 4.1354]])
Final bias: tensor([-6.2613])
Input: [0. 0.] -> Predicted Output: 0, Raw Output: 0.0019
Input: [0. 1.] -> Predicted Output: 0, Raw Output: 0.1066
Input: [1. 0.] -> Predicted Output: 0, Raw Output: 0.1098
Input: [1. 1.] -> Predicted Output: 1, Raw Output: 0.8852


!!! IMPORTANT: This example has a significant issue: the test set is the same as the training set.
This approach is used here solely for ease of explanation and should never be used in a production environment.!!!

### Exercises

#### 1.Replicate the OR Gate using a Neural Network
 Objective:
- Train a neural network to approximate the function of an OR gate.
- Compare how changing the weights or biases impacts the output of the network.

Input 1 | Input 2 | Output (OR)
| -- | -- | --|
0 | 0 | 0
0 | 1 | 1
1 | 0 | 1
1 | 1 | 1

1. Create the dataset
2. Replicate the architecture from the AND gate example
3. Change the loss function from Binary Cross-Entropy to Mean Squared Error

In [30]:
#Create the dataset
x_a = torch.tensor(0., requires_grad=True)
x_b = torch.tensor(0., requires_grad=True)
w_a = torch.tensor(0.9, requires_grad=True)
w_b = torch.tensor(0.9, requires_grad=True)

y = torch.tensor(0., requires_grad=False)

learning_rate = 0.1
epochs = 100

input_data = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
target_data = torch.tensor([[0], [1], [1], [1]], dtype=torch.float32)

class ORGateModel(nn.Module):
    def __init__(self):
        super(ORGateModel, self).__init__()
        self.linear = nn.Linear(2, 1,bias=True)

    def forward(self, x):
        x = self.linear(x)
        x = torch.sigmoid(x)
        return x

model = ORGateModel()

loss_fn = torch.nn.MSELoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    y_hat = model(input_data)
    loss = loss_fn(y_hat, target_data)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}/{epochs}, Loss: {loss.item():.4f}")

# Final weights and bias (optional)
print(f"Final weights: {model.linear.weight.data}")
print(f"Final bias: {model.linear.bias.data}")

# Test the OR gate
with torch.no_grad():
    for i in range(len(input_data)):
        x_a, x_b = input_data[i]
        y_hat = model(torch.tensor([[x_a, x_b]]))  # Model expects a batch
        print(f"Input: {input_data[i].numpy()} -> Predicted Output: {round(y_hat.item())}, Raw Output: {y_hat.item():.4f}")


Epoch 100/100, Loss: 0.0124
Final weights: tensor([[3.7077, 3.8749]])
Final bias: tensor([-1.6081])
Input: [0. 0.] -> Predicted Output: 0, Raw Output: 0.1668
Input: [0. 1.] -> Predicted Output: 1, Raw Output: 0.9061
Input: [1. 0.] -> Predicted Output: 1, Raw Output: 0.8909
Input: [1. 1.] -> Predicted Output: 1, Raw Output: 0.9975


In [ ]:
# https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html

#### 2. Build and train a network
1. Build a simple fully connected neural network with the following architecture:
    - Input layer with 2 units
    - Hidden layer with 4 units and ReLU activation
    - Output layer with 1 unit
2. Define the following loss function and optimizer:
    - Loss: Mean Squared Error (MSE)
    - Optimizer: Stochastic Gradient Descent (SGD)

The network should mimic $y = 2x_1 + 3x_2$, where $x_1$ and $x_2$ are random inputs

In [34]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split

# Define the neural network
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        # Define layers here
        self.layer1 = nn.Linear(2, 4)
        self.activation_function = nn.ReLU()
        self.layer2 = nn.Linear(4, 1)

    def forward(self, x):
        # Define forward pass
        x = self.layer1(x)
        x = self.activation_function(x)
        x = self.layer2(x)
        return x

# Create synthetic data
x = torch.rand(100, 2)
y = 2 * x[:, 0] + 3 * x[:, 1]
y = y.view(-1, 1)

# Split data into training and test sets (80% train, 20% test)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Initialize the model, loss function, and optimizer
model = SimpleNet()
criterion = nn.MSELoss()
learning_rate = 0.1
optimizer = optim.SGD(model.parameters(), lr = learning_rate)

# Training loop
for epoch in range(100):
    model.train()

    # Forward pass
    y_pred = model(x_train)

    # Compute loss
    loss = criterion(y_pred, y_train)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item()}')

model.eval()  # Set the model to evaluation mode
with torch.no_grad():
    y_test_pred = model(x_test)  # Get predictions for the test set
    test_loss = criterion(y_test_pred, y_test)  # Compute test loss

    print(f'Test Loss: {test_loss.item()}')

# Show some final predictions
print("Final Predictions (first 5 test samples):")
for i in range(5):
    print(f"Predicted: {y_test_pred[i].item():.4f}, Actual: {y_test[i].item():.4f}")



Epoch 10, Loss: 0.6862486600875854
Epoch 20, Loss: 0.440171480178833
Epoch 30, Loss: 0.24748635292053223
Epoch 40, Loss: 0.11522605270147324
Epoch 50, Loss: 0.04388982430100441
Epoch 60, Loss: 0.014136085286736488
Epoch 70, Loss: 0.0041162497363984585
Epoch 80, Loss: 0.0011946780141443014
Epoch 90, Loss: 0.0004114166949875653
Epoch 100, Loss: 0.00020959044923074543
Test Loss: 8.787450497038662e-05
Final Predictions (first 5 test samples):
Predicted: 2.0264, Actual: 2.0417
Predicted: 2.2170, Actual: 2.2060
Predicted: 3.0017, Actual: 3.0053
Predicted: 3.9368, Actual: 3.9283
Predicted: 3.2188, Actual: 3.2303
